### ISSUE TITLE
Latest releases do not work on MAC!!

### ISSUE THREAD

**Issue by Farbodart** [Dangry98/Key-Ops-Toolkit#8]
Hi

Since the _v0.1.995_ release I can't use this add-on..  
When I try to install any updated version newer than the **v0.1.99** it just give me this error:
[Errno 20] Not a directory: '/Users/Tom11/Library/Application Support/Blender/4.3/extensions/blender_org/Key_Ops_Toolkit/utils/pref_utils.py'

It show up in my Add-on list in blender but in the inactive state! and when I try to active it ...I get this:
register_class(...): already registered as a subclass 'KeyOpsPreferences'

Only  the **v0.1.99** seems to work fine.

*******
Other info:
Mac OS 15.2
Blender 4.3.2

I did restart blender in every installation process and make sure that its folder in my Add-on  folder is gone.
I have tried to copy it directly and install it in Blender menu, didn't work. 
*******

PS:
Thank you for the add-on

**Comment by Dangry98** [comment]
Thanks for the report @Farbodart ! Seems very strange. 

When you get this error:
> When I try to install any updated version newer than the v0.1.99 it just give me this error:
> [Errno 20] Not a directory: '/Users/Tom11/Library/Application Support/Blender/4.3/extensions/blender_org/Key_Ops_Toolkit/utils/pref_utils.py'

Can you please go into the consol and copy everthing, it could give some more clues:
![image](https://github.com/user-attachments/assets/df0cceeb-e064-4c27-9c06-1a272cc78b82)

**Comment by Dangry98** [comment]
I wonder if I handel paths in a bad way for mac perhaps? 🤔 Will dubbelcheck!

**Comment by Dangry98** [comment]
Wait, I think I might now! Hopfully fixed in next update! Thanks a lof the reporting the issue!

**Comment by Dangry98** [comment]
Should be fixed in v0.1.988 🤞

**Comment by Farbodart** [comment]
![Screenshot 2025-01-05 at 1 20 47 PM](https://github.com/user-attachments/assets/4e5dfc71-1fc3-47db-94b8-b9b94d33197e)

Something is solved!
* It only works if I download it manually and then copy the unzipped folder in the "extension" folder.
* Does not show up in the "Get Extensions" menu in blender when I search its name to install it! (New)
* If I drop the Zip file in blender I still get the same error. (Image of the Console and the info panel)

**Comment by Dangry98** [comment]
> If I drop the Zip file on blender UI I still get an error. (The Image)

The erros you got now seems unrealted to the add-on, seems like a Blender issue. Great that at least now it worked when you copied over the folder.

> Did not show up in the "Get Extensions" menu in blender when I searched its name to install it! (New)
Unable to replicate, check spelling since Blender is quit strict with it. 

Thanks for the report again and testing it! Closing the issue :)
